import { Space_Grotesk } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "@/assets/css/style.css";
import "./page.css";
import { AuthProvider } from "@/hooks/useAuth";
import { Toaster } from "react-hot-toast";

const space_grotesk = Space_Grotesk({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-grotesk",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Fast power tech",
  description: "Generated by steadfast",
};

export default function RootLayout({ children, initialUser }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/fav-icon.svg"
          type="image/<generated>"
          sizes="<generated>"
        />
      </head>
      <body className={space_grotesk.className}>
        <Toaster
          position="bottom-center"
          reverseOrder={true}
          toastOptions={{
            duration: 2000,
            success: {
              duration: 1000,
            },
          }}
        />
        <AuthProvider initialUser={initialUser}>{children}</AuthProvider>
      </body>
    </html>
  );
}

RootLayout.getInitialProps = async ({ ctx }) => {
  try {
    const userData = await getUser(ctx);
    return { initialUser: userData };
  } catch (error) {
    return { initialUser: null };
  }
};
